Feature about or contact page
intelsnap/website pull request #6
Opened 2020-11-08 19:49 UTC by LAEEQ18

index page is the home one

about and contact page is for review

2020-11-08 21:07 UTC, hanif-arif requested changes

2020-11-08 21:07 UTC, hanif-arif commented on LICENSE
> +PERFORMANCE OF THIS SOFTWARE.
remove license

2020-11-08 21:07 UTC, hanif-arif commented on gatsby-config.js
> +    },
no need for contentful remove

2020-11-08 21:07 UTC, hanif-arif commented on package.json
> +  "license": "0BSD",
remove

2020-11-08 21:07 UTC, hanif-arif commented on package.json
> +  "homepage": "https://github.com/gatsbyjs/gatsby-starter-hello-world#readme",
remove

2020-11-08 21:07 UTC, hanif-arif commented on package.json
> +    "bootstrap": "^4.5.3",
remove bootstrap

2020-11-08 21:07 UTC, hanif-arif commented on package.json
> +    "gatsby-source-contentful": "^3.0.6",
do not need gatsby-source-contentful

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Footer.css
> +}
Move this to Footer.js using styled components

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Footer.css
> +}
Remove separate css file

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Footer.js
> +import 'bootstrap/dist/css/bootstrap.min.css';
Remove Footer.css and bootstrap

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Navbar.css
> +}
Move to Navbar using styled components

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Navbar.js
> +    // `)
remove commented out code

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Navbar.js
> +import Nav from 'react-bootstrap/Nav';
Remove bootstrap, replace with Antd

2020-11-08 21:07 UTC, hanif-arif commented on src/components/Navbar.js
> +//import {useStaticQuery, graphql} from "gatsby";
remove commented out code

2020-11-09 01:51 UTC, LAEEQ18 commented on LICENSE
> +PERFORMANCE OF THIS SOFTWARE.
done

2020-11-09 01:52 UTC, LAEEQ18 commented on gatsby-config.js
> +    },
done

2020-11-11 22:49 UTC, LAEEQ18 commented on package.json
> +    "bootstrap": "^4.5.3",
removed

2020-11-11 22:50 UTC, LAEEQ18 commented
done

2020-11-12 00:16 UTC, closed without merging